// <auto-generated />
using System;
using HumanCRM_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanCRM_Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251215165749_AdicionarDDD")]
    partial class AdicionarDDD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("HumanCRM_Api.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .HasColumnType("TEXT");

                    b.Property<int>("Celular")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Complemento")
                        .HasColumnType("TEXT");

                    b.Property<int>("CpfCnpj")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DDD")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Obs")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrigemContato")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedeSocial")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsavelContato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rua")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("HumanCRM_Api.Models.ProspeccaoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Canal")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataProximoContato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Etapa")
                        .HasColumnType("TEXT");

                    b.Property<string>("InteressePrincipal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Necessidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrigemContato")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Probabilidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Responsavel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("ProspeccoesClientes");
                });

            modelBuilder.Entity("HumanCRM_Api.Models.ProspeccaoCliente", b =>
                {
                    b.HasOne("HumanCRM_Api.Models.Clientes", "Cliente")
                        .WithMany("Prospeccoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("HumanCRM_Api.Models.Clientes", b =>
                {
                    b.Navigation("Prospeccoes");
                });
#pragma warning restore 612, 618
        }
    }
}
